TqlCook/urls.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2021/8/1 11:46 下午
# @Author : mzt
# @Site :
# @File : urls.py
# @Software: PyCharm

from django.urls import path
from TqlCook import views

app_name = 'TqlCook'

urlpatterns = [
    path('', views.index, name='index'),
    path('search/', views.searchResult, name='searchResult'),
    path('category/<int:category_id>/', views.category, name='category'),
    path('recipe/<int:recipe_id>/', views.recipe, name='recipe'),
    # path('auth/', views.auth, name='auth'),
    path('register/', views.register, name='register'),
    path('login/', views.user_login, name='login'),
]

djangoProject/urls.py
from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from django.urls import include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('TqlCook.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

TqlCook/models.py
from django.db import models
from django.template.defaultfilters import slugify
from django.contrib.auth.models import User


class UserProfile(models.Model):
    # id = models.IntegerField(default=0, auto_created=1, primary_key=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    # name = models.CharField(max_length=64)
    # password = models.CharField(max_length=128)
    picture = models.ImageField(upload_to='profile_images', null=True)
    api = models.CharField(max_length=256, null=True)


class Category(models.Model):
    id = models.IntegerField(default=1000, auto_created=1, primary_key=True)
    category = models.CharField(max_length=64)


class Recipe(models.Model):
    id = models.IntegerField(default=2000, auto_created=1, primary_key=True)
    name = models.CharField(max_length=128)
    time = models.DateField(null=True)
    ingredient = models.TextField()
    method = models.TextField()
    views = models.IntegerField(default=0)
    images = models.TextField()


class Comment(models.Model):
    id = models.IntegerField(default=3000, auto_created=1, primary_key=True)
    recipe_id = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user_id = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    content = models.TextField()
    time = models.DateTimeField()


class RecipeCategory(models.Model):
    recipe_id = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    category_id = models.ForeignKey(Category, on_delete=models.CASCADE)


class Like(models.Model):
    recipe_id = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    user_id = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    time = models.DateField()

TqlCook/forms.py
#!/usr/bin/env python
# -*- coding: utf-8 -*-
# @Time : 2021/8/2 4:15 下午
# @Author : mzt
# @Site : 
# @File : forms.py
# @Software: PyCharm

from django import forms
from django.contrib.auth.models import User
from TqlCook.models import UserProfile, Comment


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput())

    class Meta:
        model = User
        fields = ('username', 'email', 'password', 'last_login', 'is_staff')


class UserProfileForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ('picture',)


class CommentForm(forms.ModelForm):
    content = forms.CharField(max_length=128, help_text="Please enter the content.")
    recipe_id_id = forms.IntegerField(widget=forms.HiddenInput(), initial=0)
    user_id_id = forms.IntegerField(widget=forms.HiddenInput(), initial=0)

    class Meta:
        model = Comment
        fields = ('content',)

TqlCook/views.py
from django.shortcuts import render
from TqlCook.models import Recipe, Like, UserProfile, Comment, User, RecipeCategory
from django.contrib.auth.decorators import login_required
from TqlCook.forms import UserForm, UserProfileForm, CommentForm
from django.contrib.auth import authenticate, login, logout
from django.http import HttpResponse
from django.urls import reverse
from django.shortcuts import redirect
from datetime import datetime


def index(request):
    # bing搜索没做，等着吧
    mostViewedRecipes = Recipe.objects.order_by('-views')[:6]
    context_dict = {}
    context_dict['recipes'] = mostViewedRecipes
    return render(request, 'TqlCook/index.html', context_dict)


def searchResult(request):
    return render(request, 'TqlCook/search.html')


def category(request, category_id):
    recipeList = RecipeCategory.objects.filter(category_id_id=category_id)
    recipes = []
    for recipe in recipeList:
        recipes.append(Recipe.objects.get(pk=recipe.recipe_id_id))
    context_dict = {}
    context_dict['recipes'] = recipes
    return render(request, 'TqlCook/category.html', context_dict)


def recipe(request, recipe_id):
    request.session['recipe_id'] = recipe_id
    selectedRecipe = Recipe.objects.get(pk=recipe_id)
    mostViewedRecipes = Recipe.objects.order_by('?')[:3]
    likes = Like.objects.filter(recipe_id_id=recipe_id).count()

    # 判断当前用户是否点赞
    is_like = False
    user_id = int(get_server_side_cookie(request, 'user_id', '-1'))
    if Like.objects.filter(recipe_id_id=selectedRecipe.id, user_id_id=user_id).exists():
        is_like = True

    commentsTem = Comment.objects.filter(recipe_id_id=selectedRecipe.id)
    comments = []
    for i in commentsTem:
        print(i.user_id_id)
        print(UserProfile.objects.get(pk=0))

        comments.append([i.content, User.objects.get(pk=0)])

    context_dict = {}
    # 菜谱
    context_dict['recipe'] = selectedRecipe
    # 推荐菜
    context_dict['recipes'] = mostViewedRecipes
    # 点赞
    context_dict['likes'] = likes
    # 本人点赞
    context_dict['is_like'] = is_like
    # 评论
    context_dict['comments'] = comments

    #   数据库中view+1
    selectedRecipe.views += 1
    return render(request, 'TqlCook/recipe.html', context_dict)


# def auth(request):
#     return render(request, 'TqlCook/auth.html')


def register(request):
    registered = False
    if request.method == 'POST':
        user_form = UserForm(request.POST)
        profile_form = UserProfileForm(request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user = user_form.save()
            user.set_password(user.password)
            user.save()

            profile = profile_form.save(commit=False)
            profile.user = user

            if 'picture' in request.FILES:
                profile.picture = request.FILES['picture']

            profile.save()
            registered = True

        else:
            print(user_form.errors, profile_form.errors)
    else:
        user_form = UserForm()
        profile_form = UserProfileForm()

    return render(request, 'TqlCook/index.html', context={  # 链接到主页
        'user_form': user_form,
        'profile_form': profile_form,
        'registered': registered
    })


def user_login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(username=username, password=password)
        if user:
            if user.is_active:
                login(request, user)
                request.session['user_id'] = UserProfile.user.id
                return redirect(reverse('TqlCook/index.html'))  # 链接到主页
            else:
                print("非活跃用户")
                return render(request, 'TqlCook/login.html')  # 链接登录页面
        else:
            print(f"Invalid login details: {username}, {password}")
            return render(request, 'TqlCook/login.html')  # 链接登录页面
    else:
        return render(request, 'TqlCook/login.html')  # 链接登录页面


@login_required
def user_logout(request):
    logout(request)
    return redirect(reverse('TqlCook/index.html'))


# 从服务器获取数据
def get_server_side_cookie(request, cookie, default_val=None):
    val = request.session.get(cookie)
    if not val:
        val = default_val
    return val


@login_required
def add_comment(request):
    user_id = int(get_server_side_cookie(request, 'user_id', '-1'))
    recipe_id = int(get_server_side_cookie(request, 'recipe_id', '-1'))
    # form = CommentForm(instance=user_id)

    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            form.recipe_id_id = recipe_id
            form.user_id_id = user_id
            form.save(commit=True)
            return redirect(request.get_full_path())
        else:
            print(form.errors)
    return redirect(request.get_full_path())

templates/TqlCook/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <title>
        TqlCook -
        {% block title_block %}
        {% endblock %}
    </title>

    {% block link_block %}
    {% endblock %}

    <link href="{% static 'styles/index.css' %} " rel="stylesheet" type="text/css">

    <link href="//s.chuimg.com/dist/4d5c1a6b34a8f5e1e3e3.css" rel="stylesheet" type="text/css">
    <link href="//s.chuimg.com/dist/31f8873849da7e15af56.css" rel="stylesheet" type="text/css">
    <link href="//s.chuimg.com/dist/b9ddedec44558e51bd8a.css" rel="stylesheet" type="text/css">
</head>

<body>
    <div class="topbar-outer has-bottom-border">
        <div class="topbar-container">
            <div class="topbar">
                <div class="pure-g">
                    <div class="pure-u-1-6">
                        <a href="/" class="logo">TqlCook</a>
                    </div>
                    <div class="pure-u-5-6">
                        <div class="float-left">
                            <form class="search" action="{% url 'TqlCook:searchResult' %}">
                              <input type="text" name="keyword" class="typeahead float-left" value="" placeholder="Search by ingredient or dish">
                              <input type="submit" value="Search" class="button float-left">
                            </form>
                        </div>
                        <div class="float-left">
                            <ul class="site-nav plain pure-g">
                                <li class="pure-u"><a href="/">Home</a></li>
                                <li class="pure-u"><a href="{% url 'TqlCook:category' 0 %}">Recipes</a></li>
                            </ul>
                        </div>
                        <div class="float-right clearfix">
                            <div class="user-action">
                                {% if user.is_authenticated %}
                                    Welcome, {{ user.username }}
                                {% else %}
                                    <a href="{% url 'TqlCook:login' %}">Log in</a>&nbsp;&nbsp;
                                    <a href="{% url 'TqlCook:register' %}">Register</a>
                                {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    </div>
    <!-- end of page-container -->
    </div>

    {% block body_block %}
    {% endblock %}

</body>

</html>

templates/TqlCook/login.html
{% extends 'TqlCook/base.html' %}
{% load static %}

{% block title_block %}
    Login
{% endblock %}

{% block link_block %}
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="/static/plugins/bootstrap-3.3.7-dist/css/bootstrap.css">
    <link rel="stylesheet" href="/static/css/signin.css">
{% endblock %}

{% block body_block %}
    <div class="container">
        <form id="register_form" class="form-signin" action="{% url 'TqlCook:register' %}" method="post" novalidate>
            <h2 class="form-signin-heading">Please sign in</h2>
            <label for="inputEmail" class="sr-only">Email address</label>
            <input type="email" name="user" id="inputEmail" class="form-control" placeholder="Email address" required=""
                   autofocus="">
            <label for="inputPassword" class="sr-only">Password</label>
            <input type="password" name="pwd" id="inputPassword" class="form-control" placeholder="Password"
                   required="">
            <div class="checkbox">
                <label>
                    <input type="checkbox" value="remember-me"> Remember me
                </label>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Sign in</button>
        </form>

    </div>
{% endblock %}

templates/TqlCook/recipe.html
{% extends 'TqlCook/base.html' %}
{% load static %}

{% block title_block %}
    {% if recipe %}
        {{ recipe.name }}
    {% else %}
        Unknown Recipe
    {% endif %}
{% endblock %}

{% block body_block %}
    <div class="page-outer">
        <!--begin of page-container-->
        <div class="page-container">
            <ol class="breadcrumb plain pl10" itemscope itemtype="http://schema.org/BreadcrumbList">
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="">
                    <a itemprop="item" href="/" title="Homepage"><span itemprop="name">Homepage</span></a>
                    <meta itemprop="position" content="1">
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="">
                    <a itemprop="item" href="/category/" title="Category"><span itemprop="name">Category</span></a>
                    <meta itemprop="position" content="2">
                </li>
                <li itemprop="itemListElement" itemscope itemtype="http://schema.org/ListItem" class="active">
                    <span itemprop="name">{{ recipe.name }}</span>
                    <meta itemprop="position" content="3">
                </li>
            </ol>
            <div class="pure-g">
                <!-- begin of main-panel -->
                <div class="pure-u-2-3 main-panel">
                    <!-- begin of recipe -->
                    <div>
                        <h1 class="page-title">
                            {{ recipe.name }}
                        </h1>
                        <div class="block recipe-show">
{#                            <div class="cover image expandable block-negative-margin"#}
{#                                 style="background-image: url(https://i2.chuimg.com/cee10d9a38054a3384264fa00a53ab1d_1920w_1920h.jpg?imageView2/2/w/660/interlace/1/q/90)">#}
                                <img src="/{{ recipe.images }}"
                                     alt="Method" width="660">
{#                            </div>#}
                            <div class="container pos-r pb20 has-bottom-border">
                                <div class="stats clearfix">
                                    <div class="cooked float-left">
                                        <span class="number">{{ recipe.likes }}</span>
                                        <span class="title">likes</span>
                                    </div>
                                </div>
                                <div class="collect pure-g align-right">
                                    {% if user.is_authenticated %}
                                        class="button large-button collect-button" rel="nofollow">LIKE
                                    {% else %}
                                        <a href="{% url 'TqlCook:login' %}"
                                           class="button large-button collect-button" rel="nofollow">LIKE</a>
                                    {% endif %}

                                </div>
                            </div>
                            <div class="rate-dialog block-negative-margin"></div>
                            <h2>Ingredients &nbsp;</h2>
                            <div>{{ recipe.ingredient|safe }}</div>

                            <h2 id="steps">Method &nbsp;</h2>
                            <div>{{ recipe.method|safe }}</div>
                        </div>
                    </div>
                    <!-- end of recipe -->
                    <div class="page-outer page-bottom-outer">
                        <div class="page-container">
                            <div>
                                <h2>Comment</h2>
                                <ul class="plain list question-list">
                                    {% for comment in comments %}
                                        <li class="recipe-quesions-content" data-type="question">
                                            <div class="avatar-right-2" role="question">
                                                <div class="left">
                                                    <img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAMAAAAoyzS7AAAAA1BMVEXo6Og4/a9sAAAADUlEQVR42gECAP3/AAAAAgABUyucMAAAAABJRU5ErkJggg"
                                                         data-src="https://i2.chuimg.com/d4ef51066db5442985372a69b210d941_1080w_1080h.jpg?imageView2/1/w/60/h/60/interlace/1/q/90"
                                                         alt="myshift" width="60" height="60">
                                                </div>
                                                <div class="right-top info" style="position: relative;">
                                                    {{ comment.1 }}
                                                    <span class="normal-font gray-font align-baseline">
                                                    &nbsp; &nbsp;</span>
                                                </div>
                                                <div class="right-bottom">
                                                    {{ comment.0 }}
                                                </div>
                                            </div>
                                        </li>
                                    {% endfor %}
                                </ul>
                            </div>
                        </div>
                    </div>
                    <div id="main-panel-bottom"></div>
                </div>
                <!-- end of main-panel -->

                <!-- begin of recipe-stats -->
                <div class="recipe-stats block normal-font gray-font">
                    <div class="time">created on 2020-12-04</div>
                    <div class="pv">{{ recipe.likes }} likes</div>

                    <br>
                </div>
                <!-- end of recipe-stats -->
            </div>

        </div>
        <!-- end of right-panel -->
    </div>

{% endblock %}

templates/TqlCook/register.html
{% extends 'TqlCook/base.html' %}
{% load static %}

{% block title_block %}
    Register
{% endblock %}

{% block body_block %}
    <div class="topbar-outer has-bottom-border">
        <div class="topbar-container">
            <div class="topbar">

                <div class="pure-g">
                    <div class="pure-u-1-6">
                        <a href="/" class="logo">TqlCook</a>
                    </div>
                    <div class="pure-u-2-3">&nbsp;</div>
                    <div class="pure-u-1-6 site-nav align-right">Registered?&nbsp;<a href="{% url 'TqlCook:login' %}">Login</a>
                    </div>
                </div>

            </div>
        </div>
    </div>
    <div class="page-outer">
    <!--begin of page-container-->
        <div class="page-container">
            <div class="container">
                <form id="register_form" method="post" action="{% url 'TqlCook:register' %}"novalidate>
                    <h2 class="form-signin-heading">Please register</h2>
                    <label for="inputUserId" class="sr-only">User Id</label>
                    <input type="text" name="userId" id="inputUserId" class="form-control" placeholder="User Id" required="" autofocus="">
                    <label for="inputEmail" class="sr-only">Email address</label>
                    <input type="email" name="user" id="inputEmail" class="form-control" placeholder="Email address" required="" autofocus="">
                    <label for="inputPassword" class="sr-only">Password</label>
                    <input type="password" name="pwd" id="inputPassword" class="form-control" placeholder="Password" required="">
                    <label for="inputPasswordAgain" class="sr-only">PasswordAgain</label>
                    <input type="password" name="pwdAgain" id="inputPasswordAgain" class="form-control" placeholder="Enter Password Again" required="">
                    <div class="checkbox">
                        <label>
                            <input type="checkbox" value="remember-me"> Remember me
                        </label>
                    </div>
                    <button class="btn btn-lg btn-primary btn-block" type="submit">Register</button>
                </form>
            </div> <!-- /container -->
        </div>
      <!-- end of page-container -->
    </div>
{% endblock %}

templates/TqlCook/search.html
{% extends 'TqlCook/base.html' %}
{% load static %}

{% block title_block %}
    beef - Search Result
{% endblock %}

{% block body_block %}
<div class="page-outer">
    <!--begin of page-container-->
    <div class="page-container">
        <div class="pure-g">
            <!-- begin of main-panel -->
            <div class="pure-u-2-3 main-panel">
                <div class="white-bg block">
                    <div class="pure-g">
                        <div class="pure-u-3-4 search-result-list">
                            <h1 class="page-title">You searched for "beef"</h1>
                            <div class="normal-recipe-list">
                                <ul class="list">
                                    <li>
                                        <div class="recipe recipe-215-horizontal pure-g image-link display-block">
                                            <div class="cover pure-u">
                                                <img src="{% static 'images/beef01.jpg' %}"
                                                     width="215" height="136" alt="Sirloin of Beef"/>
                                            </div>
                                            <div class="info pure-u">
                                                <p class="name">
                                                    <a href="{% url 'TqlCook:recipe' recipe_id%}">
                                                        Sirloin of Beef
                                                    </a>
                                                </p>
                                                <p class="ing ellipsis">
                                                    aged sirloin of beef、
                                                    veal stock、
                                                    fresh thyme、
                                                    peppercorns、
                                                    beef marrow bone、
                                                    sherry vinegar、
                                                </p>
                                            </div>
                                        </div>
                                    </li>
                                    <li>
                                        <div class="recipe recipe-215-horizontal pure-g image-link display-block">
                                            <a href="/recipe/106027139/" data-click-tracking-url=""
                                               data-expose-tracking-url="" target="_blank">
                                                <div class="cover pure-u">
                                                    <img src="{% static 'images/beef02.jpg' %}"
                                                         width="215" height="136" alt="Roast Sirloin of Beef"/>
                                                </div>
                                            </a>
                                            <div class="info pure-u">
                                                <p class="name">
                                                    <a href="recipe002.html">
                                                        Roast Sirloin of Beef
                                                    </a>
                                                </p>
                                                <p class="ing ellipsis">
                                                    sirloin of beef、
                                                    unsalted butter、
                                                    garlic、
                                                    thyme、
                                                    rosemary、
                                                    vegetable oil、
                                                </p>
                                            </div>
                                        </div>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="footer-outer">
    <div class="footer-container">
        <div class="pure-g">
            <div class="pure-u-3-4">

            </div>
        </div>
        <div class="pure-g">
            <div class="pure-u-3-4">
                Copyright &copy; TqlCook 2021 &nbsp;
                Manage Cookies &nbsp;
                <br>
            </div>
            <div class="pure-u-1-4 align-right">
                Inspiring food lovers everywhere
            </div>
        </div>
    </div>
</div>
{% endblock %}